accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/imageUpload/', views.imageUpload, name='imageUpload'),
    path('management/<int:page>/', views.management, name='management'),
    path('management/authority/<int:user_pk>/<int:cur_page>/', views.change_authority, name='change_authority'),
    path('findpassword/', views.findpassword, name='findpassword'),
]

portfolios/urls.py
from django.urls import path
from . import views

app_name = 'portfolios'
urlpatterns = [
    path('', views.index, name='index'),    # 포폴 게시판 메인페이지
    path('create/', views.create, name='create'),   # 게시글 생성
    path('<int:portfolio_pk>/', views.detail, name='detail'),   # 게시글 상세페이지
    path('<int:portfolio_pk>/update/', views.update, name='update'),   # 게시글 수정
    path('<int:portfolio_pk>/delete/', views.delete, name='delete'),   # 게시글 삭제
    path('portfoliolist/', views.projectlist, name='projectlist'),   # 프로젝트 리스트
    path('image/<int:image_pk>/delete/', views.image_delete, name='image_delete'),  # 이미지 삭제
]

woopolemong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolios import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('portfolios/', include('portfolios.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.processors import Thumbnail
from imagekit.models import ImageSpecField

# Create your models here.
class User(AbstractUser):

    def user_image_path(instance, filename):
        return f'images/{instance.username}/{filename}'

    intro = models.TextField(blank=True)
    my_image = models.ImageField(blank=True, upload_to=user_image_path)
    my_image_thumbnail = ImageSpecField(
        source='my_image',
        processors=[Thumbnail(200, 200)],
        format='JPEG',
        options={'quality': 80},
    )

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()


class CustomUserChangeImgForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('my_image',)



class CustomUserChangeIntroForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('intro',)

accounts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.contrib.auth import get_user_model
from accounts.forms import CustomUserCreationForm, CustomUserChangeImgForm, CustomUserChangeIntroForm
from django.contrib.auth.decorators import login_required
import random

from django.http import JsonResponse

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('portfolios:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            data = {
                'status' : 200, 
            }
            return JsonResponse(data)

    elif request.method == 'GET':
        form = AuthenticationForm()
    
    context = {
        'form' : form,
    }

    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):

    if request.user.is_authenticated:
        auth_logout(request)
    
    return redirect('portfolios:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('portfolios:index')

    pictures = ['cyk', 'jwj', 'khh', 'kty', 'sjw', 'ydh']
    picture = 'accounts/img/' + random.choice(pictures) + '.png'

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)

            return redirect('portfolios:index')

    elif request.method == 'GET':

        form = CustomUserCreationForm()

    context = {
        'form' : form,
        'picture' : picture,
    }

    return render(request, 'accounts/signup.html', context)


@require_POST
def signout(request):
    
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)

    return redirect('portfolios:index')


def findpassword():
    pass


@login_required
@require_GET
def management(request, page):
    if request.user.is_superuser:
        User = get_user_model()
        users = User.objects.all()
        users = users[(page - 1) * 10:page*10 + 1]
        user_cnt = User.objects.count()

        if user_cnt % 10  :
            last_page = user_cnt // 10 + 1
        else:
            last_page = user_cnt // 10

        user_pages = [i for i in range(1, last_page+1)]

        context = {
            'users' : users,
            'user_pages' : user_pages,
            'cur_page' : page,
            'last_page' : last_page,
        }

        return render(request, 'accounts/management.html', context)
    else:
        return redirect('portfolios:index')


@require_http_methods(['POST'])
def change_authority(request, user_pk, cur_page):
    User = get_user_model()
    user = User.objects.get(pk=user_pk)

    if request.user.is_superuser:

        if request.POST['authority'] == "2":
            user.is_superuser = 1
            user.is_staff = 1
            user.is_active = 1
        elif request.POST['authority'] == "1":
            user.is_superuser = 0
            user.is_staff = 1
            user.is_active = 1
        else:
            user.is_superuser = 0
            user.is_staff = 0
            user.is_active = 1
        
        user.save()
    else:
        return redirect('portfolios:index')

    return redirect('accounts:management', cur_page)


@require_http_methods(['GET', 'POST'])
def profile(request, username):
    user = get_object_or_404(get_user_model(), username=username)

    if request.method == 'POST':
        form = CustomUserChangeIntroForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            data = {
                'status' : 201,
            }
            return JsonResponse(data)

    elif request.method == 'GET':
        pass
        context = {
            "projects" : user.portfolio_set.all(),
            "username" : user.username,
            "my_image_thumbnail" : user.my_image_thumbnail,
            "intro" : user.intro,
        }

        return render(request, "accounts/profile.html", context)


@login_required
@require_POST
def imageUpload(request, username):

    if request.user.is_authenticated:

        if request.user.username == username:

            form = CustomUserChangeImgForm(request.POST, request.FILES, instance=request.user)

            if form.is_valid():
                form.save()

            return redirect('accounts:profile', username)
    
    return redirect('accounts:login')
    

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'accounts/css/acounts.css' %}">
<div class="login-body d-flex justify-content-center align-items-center " >
  {% comment %} 로그인폼 {% endcomment %}
    <div class="box d-flex flex-column" > 

        <p class="login-para">로그인</p>
        
        <form class="login-form d-flex flex-column" >
            {% csrf_token %}
            <div class="login-error-message"></div>
            <br>
                <input type="text" id="id_username" name="username" placeholder="사용자 이름" class="mt-2  mx-auto login-input" required>
            <br>

            <input type="password" id="id_password" name="password" placeholder="비밀번호" class="  mb-1 mx-auto login-input " required>
            <br>

            <div class="d-flex justify-content-between mb-2 mx-auto  remember-pwd-sector">
                <div>
                    <input type="checkbox" id="remeber">
                    <label for="remeber">기억하기</label>        
                </div>
                
                <a href="">비밀번호 찾기</a>
            </div>
            <div class="error-message-box text-danger "  style="text-align:center; display:none; ">
                <span class="error-message" > 유효하지 않은 계정입니다.</span>
            </div>
            <input type="submit" value="로그인" class="signup-btn mt-3  mx-auto ">
            <br>

            <div class="d-flex justify-content-center  mx-auto ">
                    
                    <a href="{% url 'accounts:signup' %}" >계정 생성하기</a>
                </p>  
            </div>
            
        </form>
        
        {% comment %} 소셜로그인폼 {% endcomment %}  

        <div class="social-login d-flex justify-content-around mx-auto ">
            <button class="social"><img width='80%' src="{% static 'accounts/img/icons/google-icon.png' %}" alt="none google img" class="social-img"></button>
            <button class="social"><img width='50%' src="{% static 'accounts/img/icons/facebook-icon.png' %}" alt="none facebook img" class="social-img pt-3"></button>
            <button class="social"><img width='50%' src="{% static 'accounts/img/icons/kakao-icon.png' %}"  alt="none kakao img" class="social-img pt-3"></button>

        </div>

  </div>

</div>


<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<script>
    const socials = document.querySelectorAll(".social")
    const loginForm = document.querySelector(".login-form")
    const id = document.querySelector("#id_username")
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
 

    socials.forEach((social) => {
        social.addEventListener('click', function () {
            alert('아직 미구현 상태입니다.')
        })
    })

    
    loginForm.addEventListener('submit', (event)=>{
        event.preventDefault()
        const username = document.querySelector('#id_username')
        const password = document.querySelector('#id_password')
        const top_box = document.querySelector('.top-box')
        const error_box = document.querySelector('.error-message-box')

        let data = new FormData()
        data.append('username', username.value)
        data.append('password', password.value)

        axios({
            method:'post',
            url :'',
            headers: {'X-CSRFToken': csrftoken},
            data,
        })
          .then((response)=>{
            if (response.data.status === 200){
                window.location.replace({% url 'portfolios:index' %});
            }else{
                username.value = ''
                password.value = ''
                error_box.style.display = 'block'
            }
          })
          .catch((error)=>{
            console.log(error)
          })
    })
</script>
{% endblock content %}  

accounts/templates/accounts/management.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mt-5 mb-5 text-center">회원관리 테이블</h1>
<div class="w-75 m-auto mt-5">
  <table class="table table-striped table-hover table-bordered">
    <thead class="text-center">
      <tr class="table-info">
        <th>
            username
        </th>
        <th>
          email
        </th>
        <th>
          last_login
        </th>
        <th>
          date_joined
        </th>
        <th>
          authority
        </th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for user in users %}
        <tr>
          <td>{{ user.username }}</td>
          <td>{{ user.email }}</td>
          <td>{{ user.last_login }}</td>
          <td>{{ user.date_joined }}</td>
          <td class="d-flex justify-content-evenly">
            <form action="{% url 'accounts:change_authority' user.pk cur_page %}" method="POST">
              {% csrf_token %}
              <select name="authority">
                {% if user.is_superuser %}
                  <option value="2" selected >관리자</option>
                  <option value="1">멤버</option>
                  <option value="0">회원</option>
                {% elif user.is_staff %}
                  <option value="2">관리자</option>
                  <option value="1" selected >멤버</option>
                  <option value="0">회원</option>
                {% elif user.is_active %}
                  <option value="2">관리자</option>
                  <option value="1">멤버</option>
                  <option value="0" selected >회원</option>
                {% endif %}
                
              </select>
              <button class='btn btn-outline-secondary ms-5'>권한 변경</button>
            </form>
            
        </tr>
      {% endfor %}
    </tbody>
  </table>
  
</div>
<div class="d-flex justify-content-center">
  
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if cur_page > 1 %}
      <li class="page-item">
        <a class="page-link" href={% url 'accounts:management' cur_page|add:-1 %} aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
      
      {% for user_page in user_pages %}
        {% if user_page == cur_page %}
          <li class="page-item active"><a class="page-link page_btn" href="{% url 'accounts:management' user_page %}">{{ user_page }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link page_btn" href="{% url 'accounts:management' user_page %}">{{ user_page }}</a></li>
        {% endif %}
      {% endfor %}

      {% if cur_page != last_page %}
        <li class="page-item">
          <a class="page-link" href={% url 'accounts:management' cur_page|add:1 %} aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
</div>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="d-flex flex-column"> 
    <div class="d-flex mx-auto mt-4" style="width:90%">
        {% comment %} 회원 프로필란 {% endcomment %}
        <div class="d-flex flex-column justify-content-between" style="width:15%; height:80vh">
            {% comment %} 회원사진 {% endcomment %}
            <div class="d-flex flex-column"> 

                <div class="d-flex flex-column p-1" style="border:solid; 1px; border-color:lightgray; border-radius: 5px;">
                    <div style=" border:solid; 1px; black; width:100px; height:100px; " class="mx-auto">
                        사-진
                    </div>
                    
                    <div style="font-size:2em">
                        {{ username }}
                    </div>

                    {% comment %} 자기소개 {% endcomment %}
                    <div class="intro-box d-flex flex-column ">
                        <div class="intro-span my-2" style= "height:40px;">{{ user.intro }}</div>
                        <form  data-user-name={{ username }} style="display:none" class="intro-form">
                            <input type="text" class="intro-input my-2" name="content" style="height:40px; width:100%">
                            <input type="submit" value="저장" class="intro-save btn m-1" style="background-color:#fcc8c8">
                        </form>
                    </div>

                    <div class="d-flex mt-1" >
                        <input type="submit" value="프로필 편집" class="intro-edit-btn btn m-1" style="background-color:#fcc8c8">
                    </div>
                </div>
    
                <div class="d-flex">
                    <input type="submit" value="회원정보 수정" class="user-info-change-btn btn m-2" style="background-color:#fcc8c8; content-box:120px">
                </div>
            </div>
        
              {% comment %} 회원탈퇴 {% endcomment %}
        
              {% if request.user.username == username %}
                <form action="{% url 'accounts:signout' %}"  method="POST">
                    {% csrf_token %}   
                    <input type="submit" value="회원탈퇴" class="btn bg-danger text-light m-2">
                </form> 
            {% endif %}
                
        </div>
        <hr>
        
        {% comment %} 작성글 목록{% endcomment %}
        <div style="width:80%" class="m-3">
            <h3>작성글</h3>
            <hr >
                <ul>
                    {% for project in projects %}
                    <a href="{% url "portfolios:detail" project.pk %}" style="text-decoration: none; color:black;"> 
                        <li>
                            <p>제목:{{ project.title }} </p>
                            <div class="d-flex">
                                {{ project.content|safe}}
                            </div>
                        </li>
                    </a> 
                    {% empty %}
                        <p>작성글이 없습니다.</p>
                    {% endfor %}
                </ul>
            <hr>
        </div>
        

        
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    const introBtn = document.querySelector('.intro-edit-btn')
    const introBox = document.querySelector('.intro-box')
    const introSpan = document.querySelector('.intro-span')
    const introForm = document.querySelector('.intro-form')
    const introInput = document.querySelector('.intro-input')
    const introSaveBtn = document.querySelector('.intro-save')
    const userChangeBtn = document.querySelector('.user-info-change-btn')

    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

    introBtn.addEventListener('click', function(event){
        introSpan.style.display='none'
        introInput.value = introSpan.innerText
        introForm.style.display='block'
        introBtn.style.display='none'
    })

    introSaveBtn.addEventListener('click', function(event){
        event.preventDefault()
        let data = new FormData()
        data.append('intro', introInput.value)
        axios({
            method:'post',
            url:`http://127.0.0.1:8000/accounts/profile/${introForm.dataset.userName}/`,
            data,
            headers:{
                'X-CSRFToken': csrftoken
            }
        })
        .then(response=>{
            introSpan.innerText = introInput.value
            introForm.style.display='none'
            introSpan.style.display='block'
            introBtn.style.display='block'
        }) 
        .catch((error) => {
            console.log(error)
        })         
    })
    


</script>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'accounts/css/acounts.css' %}">
<div class="signup-body d-flex flex-column align-items-center">
    
    <p class="signup-para">회원가입</p>
    
    <form action="" method='POST'>
        {% csrf_token %}
        <div class="d-flex justify-content-evenly align-items-center">
            <div class="w-50 m-4">
                {% bootstrap_form form %}
            </div>  
            <div class="w-50 mr-4">
                <div class="m-4 img-box">
                    <img src="{% static picture %}" alt="" class="img-fluid signup-deco">
                </div>
            </div>
        </div>
        
        <div class="d-flex justify-content-center">
            <button type='submit' class="my-2 signup-submit-btn">가입하기</button>
        </div>
    </form>
</div>

{% endblock content %}