accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/imageUpload/', views.imageUpload, name='imageUpload'),
    path('management/<int:page>/', views.management, name='management'),
    path('management/authority/<int:user_pk>/<int:cur_page>/', views.change_authority, name='change_authority'),
    path('findpassword/', views.findpassword, name='findpassword'),
]

portfolios/urls.py
from django.urls import path
from . import views

app_name = 'portfolios'
urlpatterns = [
    path('', views.index, name='index'),    # 포폴 게시판 메인페이지
    path('create/', views.create, name='create'),   # 게시글 생성
    path('<int:portfolio_pk>/', views.detail, name='detail'),   # 게시글 상세페이지
    path('<int:portfolio_pk>/update/', views.update, name='update'),   # 게시글 수정
    path('<int:portfolio_pk>/delete/', views.delete, name='delete'),   # 게시글 삭제
    path('portfoliolist/', views.projectlist, name='projectlist'),   # 프로젝트 리스트
    path('image/<int:image_pk>/delete/', views.image_delete, name='image_delete'),  # 이미지 삭제
]

woopolemong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolios import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('portfolios/', include('portfolios.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolios/models.py
# import os
from imagekit.processors import Thumbnail
from imagekit.models import ProcessedImageField, ImageSpecField
from django.db import models
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Portfolio(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    category = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    content = RichTextUploadingField()
    p_link = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Portfolio_image(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    image = models.ImageField(blank=True)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200, 300)],
        format='JPEG',
        options={'quality': 80},
    )
    # def delete(self, *args, **kargs):
    #     if self.image:
    #         os.remove(os.path.join(settings.MEDIA_ROOT, self.image.path))
    #     super(Portfolio_image, self).delete(*args, **kargs)

portfolios/forms.py
from django import forms
from .models import Portfolio, Portfolio_image
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class PortfolioForm(forms.ModelForm):
    portfolio = '[포트폴리오]'
    CATEGORY_CHOICES = [
        (portfolio, '포트폴리오'),
    ]
    category = forms.ChoiceField(choices=CATEGORY_CHOICES)

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'Title_input',
                'placeholder':'제목',
            }
        )
    )
    content = forms.CharField(
        widget=CKEditorUploadingWidget(
            attrs={
                'class':'Content_input',
                'placeholder':'내용을 입력해주세요.',
            }
        ))
    
    p_link = forms.CharField(required=False)
        
    class Meta:
        model = Portfolio
        exclude = [('author'),]

class Portfolio_imageForm(forms.ModelForm):
    image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'multiple':True,
            }
        ),
        required=False
    )
    class Meta:
        model = Portfolio_image
        exclude = [('portfolio'),]

portfolios/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_safe, require_http_methods, require_POST
from .models import Portfolio, Portfolio_image
from .forms import PortfolioForm, Portfolio_imageForm
# Create your views here.


@require_safe
def index(request):
    portfolios = Portfolio.objects.all()
    context = {
        'portfolios': portfolios,
    }
    return render(request, 'portfolios/index.html', context)


@require_safe
def detail(request, portfolio_pk):
    portfolio = Portfolio.objects.get(pk=portfolio_pk)
    images = portfolio.portfolio_image_set.all()
    context = {
        'portfolio': portfolio,
        'images': images,
    }
    return render(request, 'portfolios/detail.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            # 게시글
            form = PortfolioForm(request.POST)
            if form.is_valid():
                portfolio = form.save(commit=False)
                portfolio.author = request.user
                portfolio.save()

            # 이미지
            for photo in request.FILES.getlist('image'):
                request.FILES['image'] = photo
                image_form = Portfolio_imageForm(request.POST, request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.portfolio = portfolio
                    image.save()
            return redirect('portfolios:detail', portfolio.pk)
        else:
            form = PortfolioForm()
            image_form = Portfolio_imageForm()
        context = {
            'form': form,
            'image_form': image_form
        }
        return render(request, 'portfolios/create.html', context)
    else:
        return redirect('portfolios:projectlist')


@require_http_methods(['GET', 'POST'])
def update(request, portfolio_pk):
    portfolio = Portfolio.objects.get(pk=portfolio_pk)
    if request.user == portfolio.author:
        if request.method == 'POST':
            # 게시글
            form = PortfolioForm(request.POST, instance=portfolio)
            if form.is_valid():
                form.save()
            # 이미지
            for photo in request.FILES.getlist('image'):
                request.FILES['image'] = photo
                image_form = Portfolio_imageForm(request.POST, request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.portfolio = portfolio
                    image.save()
            return redirect('portfolios:detail', portfolio.pk)
        else:
            form = PortfolioForm(instance=portfolio)
            image_form = Portfolio_imageForm()
            db_images = portfolio.portfolio_image_set.all()
            
        context = {
                'form': form,
                'image_form': image_form,
                'db_images': db_images,
                'portfolio': portfolio,
            }
        return render(request, 'portfolios/update.html', context)
    else:
        return redirect('portfolios:detail', portfolio.pk)


@require_POST
def delete(request, portfolio_pk):
    portfolio = Portfolio.objects.get(pk=portfolio_pk)
    if request.user == portfolio.author:
        if request.method == 'POST':
            portfolio.delete()
            return redirect('portfolios:projectlist')
    else:
        return redirect('portfolios:detail', portfolio.pk)


def projectlist(request) :
    projects = Portfolio.objects.order_by('-pk')
    context = {
        'projects' : projects,
    }
    return render(request, 'portfolios/projectlist.html', context)


@require_POST
def image_delete(request, image_pk):
    if request.method == 'POST':
        image = Portfolio_image.objects.get(pk=image_pk)
        image.delete()
        data = {
            'header': 'sadf'
        }
        return JsonResponse(data)

portfolios/templates/portfolios/create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'portfolios/css/create.css' %}">
<br><br>
<div class="container">
  
  <nav class="navbar" style="background-color: #fcc8c8;">
    <div class="container-fluid">
      <p class = 'Write'> Write</p>
      <p class = 'Write_2'><a href="{% url 'portfolios:projectlist' %}" class="btn" style="background-color: rgb(255, 255, 255)">+목록</a></p>
    </div></nav><br>


  <form action="{% url 'portfolios:create' %}" method="POST" enctype="multipart/form-data" class="container-fluid">
    {% csrf_token %}
    <div class="flex-container">
      <div class = 'ms-2 Write_2' style="margin-top:8px;">카테고리 {{ form.category }}</div>
      <div class = 'w-75 Write_2'>제목: {{ form.title }}</div>
    </div>

    <br>
    <div class="container-fluid">
      <p class = 'Write_2'>Content</p>
      {{ form.media }}
      {{ form.content|safe }}
      <br>
      <br>
      <p>
        프로젝트 링크 : {{ form.p_link }}
      </p>

      <br><br>

      <div class="flex-container">
        <div>{{ image_form.as_p }}</div>
        <div><p class = 'Write_3'><button class='btn btn-lg' style="background-color: #fcc8c8;">제출</button></div>
      </div>

    </div>
  </form>
</div>

{% endblock content %}

portfolios/templates/portfolios/detail.html
{% extends 'base.html' %}

{% block content %}
<!-- <h4 style="visibility: hidden;" > {{portfolio.update_pcounter}} </h4> -->

      <div class="pdetail" style="background-color:rgba(255, 255, 255, 0.801); text-align:center;">

  
        <h1 style="padding-top:30px">{{ portfolio.title }}</h1> 
        작성일시 : {{ portfolio.created_at }}
        <br>
        {% comment %} 조회수 : {{portfolio.p_views}}  {% endcomment %}
            {% comment %} # models에 p_views = models.PostitiveIntegerField(default=0) 넣으면 조회수 수집 {% endcomment %}
        {% if request.user.is_authenticated %}
        
        <form action="{% url 'portfolios:delete' portfolio.pk %}" method = 'POST' style='display:inline'>
          {% csrf_token %}
          <button class='btn btn-md' style="background-color: #fac7c5; color: #484848; margin-top: 10px;">
            삭제
          </button>
        </form>

          &nbsp;
        <form action="{% url 'portfolios:update' portfolio.pk %}"style='display:inline'>
          <button class='btn btn-md' style="background-color: #fac7c5; color: #484848; margin-top: 10px;">
            수정
          </button>
        </form>
          {% comment %} <a style="background-color: yellowgreen;color:black;margin-left: 20px;"href="{% url 'portfolios:update' portfolio.pk %}"> 수정 </a> {% endcomment %}
        {% endif %}

          &nbsp;
        <form action="{% url 'portfolios:projectlist' %}"style='display:inline'>
          <button class='btn btn-md' style="background-color: #fac7c5; color: #484848; margin-top: 10px;">
            돌아가기
          </button>
        </form>
      
        <br>
        <hr>
        <div class="container" style='justify-content: center;'>
          {% comment %} position:flex; left:50%; {% endcomment %}
          <div class="carousel slide carousel-fade" style='margin:0 auto;'>
            <div class="row g-0" >
              <div class="col-md-6">
                <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-inner">
                    {% for image in images %}
                    <div class="carousel-item active">
                        <img src="{{ image.image.url }}" alt="none" width="650px" height='600px'>
                        {% comment %} <div class="carousel-caption d-none d-md-block">
                        test
                        </div> {% endcomment %}
                    </div>
                    {% endfor %}
                    {% comment %} <div class="carousel-item">
                      <img src="..." class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="..." class="d-block w-100" alt="...">
                    </div> {% endcomment %}
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>

              </div>
              <div class="col-md-6">
                <div class="card-body">
                  <p style="margin-top:20px; text-align:left;margin-left:320px;"><h4>{{ portfolio.content|safe }}</h4></p> 
                </div>
              </div>
            </div>
          </div>


        </div>

        <hr>
        <p style="margin-top:20px;text-align:center;"> <h6>프로젝트 링크 : <a href="{{ portfolio.p_link }}">{{ portfolio.p_link }}</a></h6></p>
            {% comment %} # 추후 해당 프로젝트 등록된 깃허브 링크 작성 {% endcomment %}

        
        
        <br>
        <br>
        <br>
        <br>
        
        
      </div>

{% endblock %}

portfolios/templates/portfolios/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'portfolios/css/index1.css' %}">

    <audio autoplay>
        <source src="{% static 'portfolios/audio/bgm.mp3' %}" type='audio/mp3'>
    </audio>

    <div id="main_index">
        <img src="{% static 'portfolios/img/index_main.png' %}" alt="..." id='index_main_img'>
        <h1 class="index_main_text">우폴레몽<br>
            <p class='sub'><span>우</span>리들의 포트<span>폴</span>리오 <span>레</span>포트 <span>모음<span></p>
        </h1>
        
    </div>
    <section class="page-section bg-white">
        <div class="container">
            <div>
                <h1 id='sogae' class="section_head">- 우폴레몽 소개 -</h1>
            </div>
            <div class="tc">
                <div class="introduce">
                    <img src="{% static 'portfolios/img/friends.png' %}" alt="..." class="collection">
                </div>
                <div class="introduce">
                    <p>
                        우폴레몽은 '우리들의 포트폴리오 레포트 모음'을 줄인 말입니다.<br>
                        처음 진행하는 프로젝트 이기때문에 많이 어설프기도 하지만<br>
                        이 프로젝트를 기반으로 앞으로 저희들의 경험을 쌓아가기 위해 진행하였습니다.<br>
                        <del>저희 6명은 삼성 청년 소프트웨어 아카데미(ssafy) 광주 1반에서 만나,<br>
                        알고리즘 공부를 위해 스터디를 이루었습니다.<br>
                        최유경 바보 (아 뭐라 써야하지)</del>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section bg-light">
        <div class="container">
            <div>
                <h1 class="section_head">- 딩코 팀 소개 -</h1>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="team_member">
                        <img class="mx-auto rounded-circle" src="{% static 'portfolios/img/kty.png' %}" alt="..." />
                        <h4>김태영</h4>
                        <p class="member_comment">코딩을 즐기는 사람</p>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="team_member">
                        <img class="mx-auto rounded-circle" src="{% static 'portfolios/img/khh.png' %}" alt="..." />
                        <h4>김희현</h4>
                        <p class="member_comment">팀의 막내</p>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="team_member">
                        <img class="mx-auto rounded-circle" src="{% static 'portfolios/img/sjw.png' %}" alt="..." />
                        <h4>심재원</h4>
                        <p class="member_comment">팀의 굳건한 맏형</p>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="team_member">
                        <img class="mx-auto rounded-circle" src="{% static 'portfolios/img/ydh.png' %}" alt="..." />
                        <h4>여도현</h4>
                        <p class="member_comment">코딩이 제일 쉬웠어요</p>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="team_member">
                        <img class="mx-auto rounded-circle" src="{% static 'portfolios/img/jwj.png' %}" alt="..." />
                        <h4>정원재</h4>
                        <p class="member_comment">기술 고문</p>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="team_member">
                        <img class="mx-auto rounded-circle" src="{% static 'portfolios/img/cyk.png' %}" alt="..." />
                        <h4>최유경</h4>
                        <p class="member_comment">응원 담당</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section bg-white">
        <div class="container">
            <div>
                <h1 class="section_head" id="project">- 포트폴리오 -</h1>
            </div>
            <div class="tc">
                <a href="{% url 'portfolios:projectlist' %}">
                    <img src="{% static 'portfolios/img/collection.png' %}" alt="..." class="collection">
                </a>
            </div>
        </div>
    </section>
    
{% endblock content %}

portfolios/templates/portfolios/projectlist.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<div class="container text-center">
  <div class="row">
    <div class="col">
    </div>
    <div class="col">
    </div>
    <div class="col">
    </div>
    <div class="col" style="text-align:right;">
      {% if request.user.is_authenticated %}
        <a href="{% url 'portfolios:create' %}" class="btn btn-secondary btn-md">글쓰기</a> &nbsp;
      {% endif %}
      <a href="{% url 'portfolios:index' %}" class="btn btn-secondary btn-md">돌아가기</a>
    </div>

  </div>
</div>
<br>

{% for project in projects %}
<div class="container"> 
<div class="card">
  <div class="card-body">
  <h1><a href="{% url "portfolios:detail" project.pk %}">{{ project.title }}</a></h1>
  {% comment %} <p><h3>{{ project.content|safe }}</h3></p> {% endcomment %}
  <p>{{ project.created_at }}</p>
  </div>
</div>
</div>
<br>
{% endfor %}



{% endblock %}

portfolios/templates/portfolios/update.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<link rel="stylesheet" href="{% static 'portfolios/css/create.css' %}">
<br><br>
<div class="container">
  
  <nav class="navbar navbar-light" style="background-color: #fcc8c8;">
    <div class="container-fluid">
      <p class = 'Write'> Write</p>
      <p class = 'Write_2'><a href="{% url 'portfolios:projectlist' %}" class="btn" style="background-color: rgb(255, 255, 255)">+목록</a></p>
    </div></nav><br>
 

  <form action="{% url 'portfolios:update' portfolio.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="flex-container">
      <div class = 'ms-2 Write_2' style="margin-top:8px;">카테고리 {{ form.category }}</div>
      <div class = 'w-75 Write_2'>제목: {{ form.title }}</div>
    </div>

    <br>
    <p class = 'Write_2'>Content</p>
    {{ form.media }}
    {{ form.content|safe }}
    <br>
    <br>
    <p>
      프로젝트 링크 : {{ form.p_link }}
    </p>
    <br><br>
    <div class="flex-container">
      <div>{{ image_form.as_p }}</div>
      <div><p class = 'Write_3'><button class='btn btn-lg' style="background-color: #fcc8c8;">제출</button></div>
    </div>
    <br>
  </form>

  <br>
  {% if db_images %}
    <div class="image-box" style = "border:0.5px solid #c7c7c7; border-radius: 5px; padding: 10px;”>
      <form action="#" method="POST">
        {% csrf_token %}
        {% for image in db_images %}
        <div class="image-line">
          <div style="margin-top:8px;"><span id=i{{ image.pk }}>{{ image.image }}</span></div>
          <div style="margin-top:8px;"> &nbsp;&nbsp; <button id="image_delete" data-pk={{ image.pk }}>삭제</button></div>
        </div>
        {% endfor %}
    </div>
  {% endif %}

  


  </form>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    const imageDelete = document.querySelectorAll('#image_delete')

    imageDelete.forEach((elem) => {
      elem.addEventListener('click', (event)=>{
        event.preventDefault()

        axios({
          method: 'POST',
          url: `/portfolios/image/${elem.dataset.pk}/delete/`,
          headers: {'X-CSRFToken': csrftoken}
        })
        .then((re)=>{console.log(re)
          const imageName = document.querySelector(`#i${elem.dataset.pk}`)
          imageName.remove()
          elem.remove()
        })          
        .catch((e)=>{console.log(e)})

      })
    })
    
  </script>
  
</div>
{% endblock content %}