accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/imageUpload/', views.imageUpload, name='imageUpload'),
    path('management/<int:page>/', views.management, name='management'),
    path('management/authority/<int:user_pk>/<int:cur_page>/', views.change_authority, name='change_authority'),
    path('findpassword/', views.findpassword, name='findpassword'),
]

portfolios/urls.py
from django.urls import path
from . import views

app_name = 'portfolios'
urlpatterns = [
    path('', views.index, name='index'),    # 포폴 게시판 메인페이지
    path('create/', views.create, name='create'),   # 게시글 생성
    path('<int:portfolio_pk>/', views.detail, name='detail'),   # 게시글 상세페이지
    path('<int:portfolio_pk>/update/', views.update, name='update'),   # 게시글 수정
    path('<int:portfolio_pk>/delete/', views.delete, name='delete'),   # 게시글 삭제
    path('portfoliolist/', views.projectlist, name='projectlist'),   # 프로젝트 리스트
    path('image/<int:image_pk>/delete/', views.image_delete, name='image_delete'),  # 이미지 삭제
]

woopolemong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolios import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('portfolios/', include('portfolios.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>우폴레몽</title>
  <!-- CSS only -->
  <link rel="icon" href={% static 'img/woopolemong-logo.png' %}>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

  <link rel="stylesheet" href= {% static 'style.css' %}>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'portfolios:index' %}">Woopolemong</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href={% url 'portfolios:index' %}#sogae>소개</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href= {% url 'portfolios:index' %}#project>프로젝트</a>
          </li>
          {% if request.user.is_authenticated %}
            <form class="nav-item" action={% url 'accounts:logout' %} method="POST">
              {% csrf_token %}
              <button class="nav-link bg-light" style="border:none;">로그아웃</button>
            </form>
            <li class="nav-item">
              <a class="nav-link" href= {% url 'accounts:profile' user.username %}>내 프로필</a>
            </li>
            {% if request.user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link"  href="{% url 'accounts:management' 1 %}">관리자 페이지</a>
            </li>
            {% endif %}
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  
  
  
  {% endblock content %}
  <div class="jumbotron text-center mt-5 mb-0 sticky-end">
    <p>© 2022 created by DingCo</p>
  </div>
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>